name: Build Windows Desktop App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: win-installer
          path: dist/
